# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vain_routes}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Stawarz"]
  s.date = %q{2011-05-02}
  s.description = %q{Vain routes is a Rails engine that enables you to view your routes in a filterable online view.}
  s.email = %q{ryan at stawarz dot com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/vain_routes/routes_controller.rb",
    "app/views/layouts/vain_routes/base.html.erb",
    "app/views/vain_routes/routes/_route.html.erb",
    "app/views/vain_routes/routes/index.html.erb",
    "config/routes.rb",
    "doc/screenshot.png",
    "doc/search_snapshot.PNG",
    "doc/sort_snapshot.PNG",
    "lib/vain_routes.rb",
    "lib/vain_routes/engine.rb",
    "public/vain_routes/data_tables/css/demo_page.css",
    "public/vain_routes/data_tables/css/demo_table.css",
    "public/vain_routes/data_tables/css/demo_table_jui.css",
    "public/vain_routes/data_tables/images/Sorting icons.psd",
    "public/vain_routes/data_tables/images/back_disabled.jpg",
    "public/vain_routes/data_tables/images/back_enabled.jpg",
    "public/vain_routes/data_tables/images/favicon.ico",
    "public/vain_routes/data_tables/images/forward_disabled.jpg",
    "public/vain_routes/data_tables/images/forward_enabled.jpg",
    "public/vain_routes/data_tables/images/sort_asc.png",
    "public/vain_routes/data_tables/images/sort_asc_disabled.png",
    "public/vain_routes/data_tables/images/sort_both.png",
    "public/vain_routes/data_tables/images/sort_desc.png",
    "public/vain_routes/data_tables/images/sort_desc_disabled.png",
    "public/vain_routes/data_tables/js/jquery.dataTables.js",
    "public/vain_routes/data_tables/js/jquery.dataTables.min.js",
    "public/vain_routes/data_tables/js/jquery.dataTables.min.js.gz",
    "public/vain_routes/data_tables/js/jquery.js",
    "public/vain_routes/images/Sorting icons.psd",
    "public/vain_routes/images/back_disabled.jpg",
    "public/vain_routes/images/back_enabled.jpg",
    "public/vain_routes/images/favicon.ico",
    "public/vain_routes/images/forward_disabled.jpg",
    "public/vain_routes/images/forward_enabled.jpg",
    "public/vain_routes/images/oak_background_texture.jpg",
    "public/vain_routes/images/sort_asc.png",
    "public/vain_routes/images/sort_asc_disabled.png",
    "public/vain_routes/images/sort_both.png",
    "public/vain_routes/images/sort_desc.png",
    "public/vain_routes/images/sort_desc_disabled.png",
    "public/vain_routes/stylesheets/base.css",
    "public/vain_routes/stylesheets/data_table_jui.css",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_diagonal-maze_20_6e4f1c_10x10.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_diagonal-maze_40_000000_10x10.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_10_eceadf_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_10_f8f7f6_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_15_eceadf_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_15_f7f3de_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_15_ffffff_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_65_654b24_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-bg_fine-grain_68_b83400_60x60.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-icons_222222_256x240.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-icons_3572ac_256x240.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-icons_8c291d_256x240.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-icons_b83400_256x240.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-icons_fbdb93_256x240.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/images/ui-icons_ffffff_256x240.png",
    "public/vain_routes/stylesheets/jui-pepper-grinder/jquery-ui-1.8.11.custom.css",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_flat_55_fbec88_40x100.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_glass_75_d0e5f5_1x400.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_glass_85_dfeffc_1x400.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_glass_95_fef1ec_1x400.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_inset-hard_100_f5f8f9_1x100.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-bg_inset-hard_100_fcfdfd_1x100.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_217bc0_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_2e83ff_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_469bdd_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_6da8d5_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_cd0a0a_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_d8e7f3_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/images/ui-icons_f9bd01_256x240.png",
    "public/vain_routes/stylesheets/jui-redmond/jquery-ui-1.8.11.custom.css",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/vain_routes_spec.rb"
  ]
  s.homepage = %q{http://github.com/rstawarz/vain_routes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Vain Routes enables you to view your routes from a web page.}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/vain_routes_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0"])
  end
end

